### ISSUE TITLE
Add keyboard shortcuts to move to next and previous sentences

### ISSUE THREAD

**Issue by mzraly** [LuteOrg/lute-v3#140]
Sometimes you want to focus on entire sentences, one at a time.  Lute provides navigation by word using arrow keys but not by sentence.  It would be nice to have keyboard shortcuts for sentence navigation that would let the user get in a rhythm of entering the keyboard shortcut for next sentence, then t to translate the sentence, then repeating the pair of keyboard shortcuts as needed.

Candidates:
* Using arrow up and down to navigate sentences would be consistent with arrow left and right to navigate words, but they are already used to increase or decrease the word status.  While I personally would prefer using something like + and - to increment and decrement status and then use arrow up and down for sentence navigation I do recognize that changing keyboard shortcuts may annoy some people.
* Using Shift plus arrow up and down would fit in with using Shift plus arrow left and right to navigate among unknown words, but is a bit inconsistent with the translation and copy commands t and c, where Shift implies operating at the paragraph level.

**Comment by jzohrab** [comment]
Right, this is like "sentence mode" in LingQ?  I've thought briefly about it but don't have a good implementation idea for that yet.  Lute treats book pages as pages, more like physical books.

Perhaps there could be some kind of "sentence mode" where the existing sentences on a current page are hidden or something, so that you could focus on just the one at a time.  Optionally, the "page break" idea (#31) would let you break a book into separate pages.

For the keyboard shortcuts, one possibility would be something like customizable keyboard shortcuts (#141, just added).

**Comment by jzohrab** [comment]
Customizable shortcuts were added in #141 , so I added some customizable hotkey "slots" to move to prev, next sentences, tested and works ok.  Fixed in `develop`, will be in next launch.

**Comment by jzohrab** [comment]
Launched in 3.5.9.
