### ISSUE TITLE
Import from Calibre library

### ISSUE THREAD

**Issue by GrimPixel** [LuteOrg/lute-v3#252]
**Is your feature request related to a problem? Please describe.**

A Calibre user may have books already in a library. It would be convenient if books there are imported to Lute in batch.

**Describe the solution you'd like**

Read the Calibre library and add them in Lute.

**Comment by jzohrab** [comment]
Unfortunately this won't be easily possible.  Lute is a web app and so doesn't necessarily have access to the system libraries necessary for Calibre imports.  In addition, since (at this point) Lute is still in early stages, we can't consider features that will only be applicable to a relatively small segment of the user base.

I'll leave this open, but will tag it as "wont-fix" for now due to the above reasons.  It would be _nice_ to support such a thing, but it feels out of scope at least for now.

**Comment by jzohrab** [comment]
Closing to manage the backlog only.
