### ISSUE TITLE
Add 'Actions' button to Books index

### ISSUE THREAD

**Issue by M-Biggles** [LuteOrg/lute-v3#316]
We have actions on the Terms page, and it would work nicely on the Books listing. Initially, you could add 'Create new book' and 'Import web page' from the Books menu.

**Comment by jzohrab** [comment]
Total ballparks for dev estimates:

- copy the "Actions" dropdown code from the term listing
- handle confirmation messages when multiple books selected for delete or archive
- add checkbox to book listing, like term listing
- fix tests to run the actions from the actions button

**Comment by jzohrab** [comment]
Instead of a big actions button on the book listing which has some more code changes and challenges, a small step forward would be to use an "actions" list for each row:

> ![Image](https://github.com/jzohrab/lute-v3/assets/1637133/cfb9aac8-a639-432b-80ff-3da6ee7fd8da)

At least it lets me quickly add some more actions to the book list, so a bit of progress.

started in `wip_316_book_actions_list`

**Comment by jzohrab** [comment]
Closing for now to clear up the backlog, the current book dropdown works well enough.
