### ISSUE TITLE
BookStats remaining after books have been deleted

### ISSUE THREAD

**Issue by cblanken** [LuteOrg/lute-v3#460]
**Description**
I'm not sure if it's intended but it seems like BookStat records remain even when a Book has been deleted.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Start Lute with default database
2. Delete books
3. Check `bookstats` in SQLite Browser or via `sqlite`
4. See bookstats for deleted books still exist

**Screenshots**

For example, the `bookstats` after having deleted all but a few of the default books.
![image](https://github.com/user-attachments/assets/58e56b0d-8082-459b-be6f-0e43b5c00493)
![image](https://github.com/user-attachments/assets/007f58f6-b4f0-47e4-8e2e-09c1b3736818)

**Comment by jzohrab** [comment]
Whoops, not intended.  Not a big deal, but should be cleaned up just for tidiness.

**Comment by jzohrab** [comment]
Thanks @cblanken for the issue.  This was actually a very good catch: sqlite doesn't cascade deletes unless a pragma is set.  For everything else the Lute data model took care of things properly but setting the pragma is still a good thing to do, so I added that and added a few checks and cleanup things.

Fixed in `develop` 👍

**Comment by jzohrab** [comment]
Launched in 3.8.0.
