### ISSUE TITLE
Images propagate up to parent when child is updated

### ISSUE THREAD

**Issue by bwkimmel** [LuteOrg/lute-v3#496]
**Description**

When updating anything about a child term and saving those changes, if the child term has an image and the parent does not, the child term's image gets applied to the parent.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

- Create a term "parent"
- Create a child term "child" with "parent" as it's parent.
- Add an image to the child term (this will get applied to both terms when saved, which is arguably not the wrong thing to do *here*).
- Navigate to the "parent" and delete the image.
- Navigate to the "child" term from there click on the link to "parent" (which will cause child to be saved before navigating away).
- Parent now has the child term's image reapplied.

**Screenshots**

If it will be helpful, add screenshots.

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Arch Linux under WSL2 (Windows 11)
- Browser (e.g., chrome, safari): Brave
- How you've installed Lute (Docker, python, source): Source
- Version: 3.5.6

**Comment by jzohrab** [comment]
Thanks @bwkimmel -- I'm assuming that this issue is for exactly the scenario above; i.e. when **changing an existing child**, the existing parent shouldn't get the image or translation.

If **creating a new child term**, the parent will continue to get the image and translation if needed, because the user (me) has likely just been lazy when creating that parent at some point in the past.

**Comment by jzohrab** [comment]
Change made in `develop` branch, in commit d045ad26207c81.  With this, editing an **existing** child doesn't also propagate the translation and image data to the parent, even if that data is missing in the parent.

**Comment by jzohrab** [comment]
Launched in 3.5.8.
