### ISSUE TITLE
Installing Error (Newbie on Python

### ISSUE THREAD

**Issue by Hakan108** [LuteOrg/lute-v3#507]
Hello,

While installing it I got an error message as follow: 

  _When you're finished reading, stop this process
  with Ctrl-C or your system equivalent.

  Lute v3.5.8 is running.  Open a web browser, and go to:

      http://localhost:5001

Error during startup:
Type: <class 'OSError'>
[WinError 10049] The requested address is not valid in its context

Please check your setup and try again.
Ask for help on Discord, or report an issue on GitHub.
Additionally, help is available with --help_

**Comment by jzohrab** [comment]
Ah thanks @Hakan108 - that's a new one for me.  Google might have something useful to say.

**Comment by jzohrab** [comment]
Hi @Hakan108 -- this is happening due to your computer configuration, so hopefully I can guide you to fix it.  Maybe not though, I'm flying blind, so it might be best to chat on discord with me or others!

Some background: Lute starts the server running on IP 0.0.0.0 on your system, so that any other devices like tablets, phones, on your network can also connect to Lute using your computer's IP.  It seems like your computer doesn't have that set up, or maybe it has some rules blocking its use.

Maybe you can configure the firewall to allow incoming connections for 0.0.0.0 on the specified port (e.g., 5000 or 5001). In Windows, go to Control Panel > System and Security > Windows Defender Firewall > Advanced settings, and add a new Inbound Rule for the port.

Give that a shot, see if you can sort it out.  Check on Discord too, and google too.

(I should add a "--local" flag to the startup or something like it, so that it starts running on a different IP address (still localhost, but only available on that machine), which should also resolve this issue.  But see if you can sort out your computer network configuration first)

Cheers!

**Comment by jzohrab** [comment]
ps - if you can't sort it out, I've added a "--local" flag that you use at startup which _should_ resolve this issue.  Should!!  That will be in the next release.

`python -m lute.main --local`

**Comment by jzohrab** [comment]
I'm marking this as fixed and done :-) but that's only on the code side for the next release.  See if you can sort out the configuration and let me know.  Thanks!

**Comment by jzohrab** [comment]
Hi there, I've added a `--local` flag to the startup, so you should be able to use that.  Please update and let me know!  I'll close this issue for now, we can reopen it if needed.
